format = '''
 $jobs$sudo$directory$character
'''
right_format = '''
$cmd_duration$git_branch$git_commit$git_status
'''

[character]
success_symbol = '[󰋅](green)'
error_symbol   = '[󰋅](red)'
vimcmd_symbol  = '[󰴈](green)'

[directory]
format = '[](purple)[$read_only$path](bg:purple fg:bold black)[](purple) '
read_only = " "

[sudo]
disabled = false
format   = '[$symbol](fg:bold cyan) '
symbol   = ""

[cmd_duration]
format = ' [](yellow)[󰞌 $duration](bg:yellow fg:bold black)[](yellow)'

[jobs]
symbol = '󰫢'

[git_branch]
format = ' [](cyan)[$symbol $branch(:$remote_branch)](bg:cyan fg:bold black)'
symbol = ''

[git_commit]
format = '[ {$hash}](bg:cyan fg:bold black)'

[git_status]
format = '[ (\[$all_status\])\($ahead_behind\)](bg:cyan fg:bold black)[](cyan)'
ahead      = ''
behind     = ''
diverged   = ''
up_to_date = ''
renamed    = '/'
deleted    = '-'
